title = "HMPPS Gitleaks configuration"
[extend]
path = "./node_modules/@ministryofjustice/hmpps-precommit-hooks/config.toml"

[[allowlists]]
description = "global allow list"
paths = [
  '''.*\.test\.ts''',
]
